pipeline:
  name: Hello-world-function
  identifier: Helloworldfunction
  projectIdentifier: Cloud_Functions
  orgIdentifier: CCRA
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Joses_GitHub
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Audit
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Build
                  identifier: Build
                  spec:
                    connectorRef: account.harnessImage
                    image: node:18-alpine
                    shell: Sh
                    command: |-
                      npm install
                      mkdir deploy
                      mv index.js package.json deploy/
              - step:
                  type: GCSUpload
                  name: Upload Code
                  identifier: Upload_Code
                  spec:
                    connectorRef: commercetoolsacceleratordev
                    bucket: hello-world-function-source
                    sourcePath: deploy
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: org.CTAcluster
              namespace: harness-dmi-sandbox
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
